version: "3.0"
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_DB=work_time_records
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_user
      - db_password
    ports:
      - "5432:5432"
    networks:
      - work_time_records_network
  backend:
    image: node:lts
    volumes:
      - ./wtr_backend_project:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=/run/secrets/db_user
      - DB_PASSWORD=/run/secrets/db_password
    networks:
      - work_time_records_network 
networks:
  work_time_records_network:
    driver: bridge
secrets:
  db_user:
    file: ./db_user
  db_password:
    file: ./db_password