'use client';
import SideMenuComponent from '@/components/global/sideMenuComponent';
import { Box, ChakraProvider } from '@chakra-ui/react';

// title and description tags shall not be used but export as a constant
// nextjs handles it 

export const metadata = {
    title: 'ic0045 project',
    description: 'Generated by Next.js'
}

// root component, everything inside <body> will be re-rendered
// it can be used within nested components

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <SideMenuComponent></SideMenuComponent>
            {children}
        </>
    )
}
